[project]
name = "birdclef"
version = "0.1.0"


[tool.ruff]
line-length = 88
select = ["E", "F", "W", "I", "UP", "N", "ANN"] # Example selection, tailor this
ignore = ["E501", "ANN101", "ANN102", "ANN401"] # Ignore missing types for self/cls, Any types if necessary initially

[tool.ruff.lint.isort]
known-first-party = ["birdclef"] # Tell isort about your project structure

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true # Start with this, try to remove later by adding stubs
# Add plugin for torch if needed for better type inference
# plugins = ["torch.distributed.mypy_plugin"] # Example

[tool.pyright]
exclude = ["**/node_modules", "**/__pycache__", "./stubs"]
stubPath = "./stubs"
reportMissingImports = "warning" # Or "error" for stricter checks
reportUndefinedVariable = "error"
pythonVersion = "3.12"
# Add venvs paths if needed
# venvPath = "."
# venv = ".venv"
